import Breadcrumb from "@/components/Breadcrumb";
import Header from "@/components/Header";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Partners",
  description: "Generated by create next app",
};

export default function PartnersLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        <Breadcrumb />
        {children}
      </body>
    </html>
  );
}
